CREATE TABLE [dbo].[Table]
(
	[家长编号] VARCHAR(6) NOT NULL PRIMARY KEY, 
    [打印编号] VARCHAR(8) NOT NULL, 
    [接待人] VARCHAR(12) NOT NULL, 
    [接入时间] DATETIME NOT NULL, 
    [家长称呼] VARCHAR(12) NOT NULL, 
    [联系方式] VARCHAR(11) NOT NULL, 
    [家教地址（简单）] VARCHAR(50) NOT NULL, 
    [家教地址（详细）] VARCHAR(50) NOT NULL, 
    [年级科目] VARCHAR(50) NOT NULL, 
    [学员性别] NCHAR NOT NULL, 
    [家教价格] FLOAT NOT NULL, 
    [家教时间] VARCHAR(50) NOT NULL, 
    [教员要求（性别）] NCHAR(1) NULL, 
    [教员要求（地域）] VARCHAR(20) NULL, 
    [教员要求（年级）] VARCHAR(10) NULL, 
    [教员要求（专业）] VARCHAR(20) NULL, 
    [教员要求（其他）] VARCHAR(50) NULL, 
    [家教状态] VARCHAR(2) NOT NULL, 
    [重要备注] VARCHAR(50) NULL, 
    [缴费状态] VARCHAR(4) NOT NULL, 
    [缴费时间] DATETIME NULL, 
    [教员编号] VARCHAR(10) NULL, 
    [进行状态] VARCHAR(2) NULL, 
    [经办时间] DATETIME2 NULL, 
    [经办人] VARCHAR(12) NULL, 
    [是否缴费] VARCHAR NULL, 
    [备注] VARCHAR(50) NULL
)
